security:
    encoders:
        App\Entity\Utilisateur:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: pseudonyme
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\Authenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: index
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Tous les rôles : [ROLE_USER, ROLE_ADHERENT, ROLE_SECRETAIRE]
        # Pour se connecter :
        # Pseudo : mdp : Roles attribués
        # Maxime : 123 : user
        # Simeon : 123 : adherent, user
        # Will   : 123 : Secretaire, adherent, user
        - { path: ^/ligues, roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/bureaux, roles: ROLE_SECRETAIRE}
        - { path: ^/sallesreservable, roles: ROLE_SECRETAIRE}
        - { path: ^/newcatsaller, roles: ROLE_SECRETAIRE }
        - { path: ^/reserver, roles: ROLE_ADHERENT}

